### PR TITLE
Using Bootstrap

### PR DESCRIPTION
**Pull request by alexisbec**
This project requests students to build a replica of the news site Newsweek.com using the Bootstrap framework.

### CODE REVIEW

**Comment by PhillipUg** [comment]
# Invalid Submission 🔴 

- [x] Your pull Request should have a meaningful title and short summary. Ensure to do this for all your future projects before submitting for review. 

**Friendly reminder:** You should make sure that your repo looks professional before review.
Please take a step back and read a lesson here https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/.
Then apply 3 simple rules from this lesson (it will be easy as you can use a template provided there).
This Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready!

For any assistance feel free to reach out to me on slack as **Phillip Musiime**

**Review by PhillipUg — CHANGES_REQUESTED** [review]
Hey team, 👋

You have done an amazing job implementing the project requirements for this project so far!

However, there are still some changes 👇 you need to implement to approve this request 🔍

### Changes Required ♻️ 

- [x] You are required to use bootstrap wherever possible, so please use less CSS and more bootstrap, thats the whole point of this project. You can read more about it here ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/using_bootstrap/bootstrap_classes_requirement.png) and [pathright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59540308/))

- [x] You are missing a `Top Story` section. I realise that you mistakenly named it `featured stories`. please correct this

#### Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack as **Phillip Musiime**
I would be happy to help! 👩‍💻 

Happy coding 🤓

**Review by ebeagusamuel — CHANGES_REQUESTED** [review]
# Changes Required :recycle: 
Hello team :wave: 
Your project looks nice and I can see that you have implemented some of the changes requested by the previous TSE, however, there are still some changes that you still need to make to get this project approved.
- [x] Please avoid the use of `!important` in your CSS. According to MDN, "Using! important, however, is bad practice and should be avoided because it makes debugging more difficult by breaking the natural cascading in your stylesheets."
- optional
- [x] You can try to use bootstrap classes to implement some of the stylings you are writing directly in your css. This project is about using bootstrap so it makes sense to maximize bootstrap to its fullest in this project.

Do request another review when you are done with the changes.
slack(@ebeagusamuel)

**Review by ElijahTobs — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

## Hi @alexisbec and @vichuge 

Good job implementing the change as requested by the previous TSE :+1: 
However, there's still a little more to be done before your project can be approved.

 ## [REQUIRED]
* [x] Your navbar should contain the Sign in and Subscribe links, not a **p tag** and **a button** ([link to page](https://www.newsweek.com/))
* [x] It contains main navigation links, not **p tags** ([link to page](https://www.newsweek.com/))
* [x] Since this is a Bootstrap project, you should add **Bootstrap** to your **Built With** in the README

## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

**Review by ElijahTobs — APPROVED** [review]
# Status: Approved! :tada: 

Congratulations! @alexisbec and @vichuge  :man_dancing: 

Good job implementing the required changes.

### You can now merge and submit.

## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

**Pull request merged**
